=== antsanchez93/LM_1617_Antonio_Sanchez/XML and DTD/Sanchez_Adamuz_Antonio_LM_U2_T2DTD Rubric/ejercicio2.dtd
<!ELEMENT lettera (#PCDATA|cliente|ordine|responsable)*>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT ordine (articolo+)>
<!ATTLIST ordine num CDATA #REQUIRED>
 <!ELEMENT articolo (codice, descr)>
       <!ELEMENT codice (#PCDATA)>
       <!ELEMENT descr (#PCDATA)>
<!ELEMENT responsable (#PCDATA| tit)*>		      
<!ELEMENT tit (#PCDATA)>

=== antsanchez93/LM_1617_Antonio_Sanchez/XML and DTD/Sanchez_Adamuz_Antonio_LM_U2_T2DTD Rubric/XML_EJ2.xml
<?xml version="1.0"?>
<!DOCTYPE lettera SYSTEM "ejercicio2.dtd">
 <lettera>
    Gentile<cliente>tal dei tali</cliente>,
    la imformiamo che i seguenti articoli da lei ordinati non sono piu disponibili a maggazzino:
    <ordine num="1234">
        <articolo>
            <codice>1</codice>
            <descr>articolo 1</descr>
        </articolo>
        <articolo>
            <codice>5</codice>
            <descr>articolo 5</descr>
        </articolo>
    </ordine>
    Cordiali saluti,
    <responsable><tit>dr.</tit>Mario Rossi</responsable>
 </lettera>
